# Interactive compenent

## COVID-19 situation by ethinicity 

This is a consolidation of our previous findings. This interactive plot enables readers to compare different statistics of their interests by themselves by clicking on different buttons

This bar charts contain infected and death cases by ethnicity. 'Infected percentage in ratio' means the number of infected cases in one race divided by all infected cases. It shows the distribution of COVID-19 infected cases by ethnicity. 'Deaths percentage in ratio' means the number of death cases in one race divided by all deaths cases. It shows the distribution of COVID-19 death cases by ethnicity. 'Ethnicity percentage in ratio' means the distribution of the US population by ethnicity.

By comparing these three bar charts, we can get a direct sense of whether there are differences between the actual ethnicity ratio in US and true deaths/cases ratio by ethnicity. Moreover, we add cases in 1000 and deaths in 1000 to directly shows which race is affected most by COVID-19 and which is the least.  Thus, we can get a intuitive idea of whether the COVID-19 situation differs by race. Otherwise, in the static bar plot, we cannot get the direct sense of how the ratio change by race. An interactive map has the advantages to compare both how ratio differs by ethnicity and how ratio differs in expected value(real ethnicity ratio) and true value(real death cases/infected races).


<script src="https://d3js.org/d3.v6.min.js"></script>


<!-- Add 3 buttons -->
<button onclick="update(data1)">Infected percentage in ratio</button>
<button onclick="update(data2)">Deaths percentage in ratio</button>
<button onclick="update(data3)">Ethnicity percentage in ratio</button>
<button onclick="update(data4)">Cases in 1000</button>
<button onclick="update(data5)">Deaths in 1000</button>




<!-- Create a div where the graph will take place -->
<div id="my_dataviz"></div>


<script>

// create 2 data_set
var data1 = [
   {group: "White", value: 58},
   {group: "Hispanic", value: 24.1},
   {group: "Black", value: 13.0},
   {group: "Asian", value: 3.1},
   {group: "AIAN", value: 1.2},
   {group: "Multiracial", value: 0.9},
   {group: "NHPI", value: 0.31}
  
];

var data2 = [
   {group: "White", value: 61},
   {group: "Hispanic", value: 18.8},
   {group: "Black", value: 15.1},
   {group: "Asian", value: 3.5},
   {group: "AIAN", value: 1},
   {group: "Multiracial", value: 0.4},
   {group: "NHPI", value: 0.2}
  
];

var data3 = [
   {group: "White", value: 61.2},
   {group: "Hispanic", value: 15.3},
   {group: "Black", value: 13.4},
   {group: "Asian", value: 5.9},
   {group: "AIAN", value: 1.3},
   {group: "Multiracial", value: 2.7},
   {group: "NHPI", value: 0.2}
];

var data4 = [
   {group: "White", value: 52.4},
   {group: "Hispanic", value: 87.7},
   {group: "Black", value: 53.9},
   {group: "Asian", value: 5.9},
   {group: "AIAN", value: 28.9},
   {group: "Multiracial", value: 18.5},
   {group: "NHPI", value: 76.1}
];

var data5 = [
   {group: "White", value: 1.5},
   {group: "Hispanic", value: 1.8},
   {group: "Black", value: 1.6},
   {group: "Asian", value: 0.9},
   {group: "AIAN", value: 1.1},
   {group: "Multiracial", value: 0.2},
   {group: "NHPI", value: 1.2}
];

// set the dimensions and margins of the graph
var margin = {top: 20, right: 3, bottom: 20, left: 60},
    width = 460 - margin.left - margin.right,
    height = 400 - margin.top - margin.bottom;

// append the svg object to the body of the page
var svg = d3.select("#my_dataviz")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")");

// X axis
var x = d3.scaleBand()
  .range([ 0, width ])
  .domain(data1.map(function(d) { return d.group; }))
  .padding(0.2);
svg.append("g")
  .attr("transform", "translate(0," + height + ")")
  .call(d3.axisBottom(x))

// Add Y axis
var y = d3.scaleLinear()
  .domain([0, 100])
  .range([ height, 0]);
svg.append("g")
  .attr("class", "myYaxis")
  .call(d3.axisLeft(y));

// A function that create / update the plot for a given variable:
function update(data) {

  var u = svg.selectAll("rect")
    .data(data)

  u
    .enter()
    .append("rect")
    .merge(u)
    .transition()
    .duration(1000)
      .attr("x", function(d) { return x(d.group); })
      .attr("y", function(d) { return y(d.value); })
      .attr("width", x.bandwidth())
      .attr("height", function(d) { return height - y(d.value); })
      .attr("fill", "#69b3b2")
}

// Initialize the plot with the first dataset
update(data1)

</script>
